/**
 * Reads every public/blogs/*.md file, validates its frontmatter, and emits
 * src/generated/blogIndex.ts — the generated single source of truth for
 * blog post listing metadata (replaces the old hand-maintained blogPosts
 * array in src/data.ts). Run via `npm run generate:blog`, and automatically
 * via the predev/prebuild npm hooks.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { z } from 'zod';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BLOGS_DIR = path.join(ROOT, 'public', 'blogs');
const OUTPUT_FILE = path.join(ROOT, 'src', 'generated', 'blogIndex.ts');

const frontmatterSchema = z.object({
  title: z.string().min(1, 'title is required'),
  date: z
    .string()
    .min(1, 'date is required')
    .refine((val) => !Number.isNaN(Date.parse(val)), {
      message: 'date must be a value Date.parse() can understand, e.g. "July 24, 2026"',
    }),
  excerpt: z.string().min(1, 'excerpt is required'),
  tags: z.array(z.string()).default([]),
  image: z.string().optional(),
});

async function main() {
  const files = (await readdir(BLOGS_DIR)).filter((f) => f.endsWith('.md'));

  const posts = await Promise.all(
    files.map(async (file) => {
      const slug = file.replace(/\.md$/, '');
      const raw = await readFile(path.join(BLOGS_DIR, file), 'utf-8');
      const { data } = matter(raw);

      const result = frontmatterSchema.safeParse(data);
      if (!result.success) {
        const issues = result.error.issues
          .map((issue) => `  - ${issue.path.join('.') || '(root)'}: ${issue.message}`)
          .join('\n');
        throw new Error(`Invalid frontmatter in public/blogs/${file}:\n${issues}`);
      }

      return { slug, ...result.data };
    }),
  );

  posts.sort((a, b) => Date.parse(b.date) - Date.parse(a.date));

  const banner =
    '// AUTO-GENERATED by scripts/generate-blog-index.ts — do not edit by hand.\n' +
    '// Run `npm run generate:blog` to regenerate (also runs automatically before dev/build).\n\n';

  const body = `export const blogPosts = ${JSON.stringify(posts, null, 2)} as const;\n`;

  await mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
  await writeFile(OUTPUT_FILE, banner + body);

  console.log(`Generated ${path.relative(ROOT, OUTPUT_FILE)} with ${posts.length} post(s).`);
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
